### ISSUE TITLE
needs GLONASS support

### ISSUE THREAD

**Issue by Joe-Simons** [samGNSS/radar#1]
Теперь это история о том, как все
Моя жизнь стала перевернуто-перевернулось
И я хотел бы занять минуту
Просто сидеть прямо там
Я расскажу вам, как я стал князем в городе под названием Bel-Air

В Западной Филадельфии родился и вырос
На спортивной площадке было где я провел большую часть моих дней
CHILLIN 'из Maxin' релаксин 'все круто
И все расстреливает би-мяч за пределы школы
Когда пара парней, которые были до ни к чему хорошему
Начал неприятности в моем районе
Я получил в одной маленькой борьбе и моя мама испугалась
Она сказала: "Ты двигаешься" с тетей и дядей в Bel-Air ».

Я просил и умолял ее день за днем
Но она упаковала свой чемодан и послал меня на моем пути
Она дала мне поцелуй, а потом она дала мне свой билет.
Я положил на Walkman и сказал: "Я мог бы также удар его."

Первый класс, йо, это плохо
Питьевая апельсиновый сок из шампанского.
Является ли это то, что люди Bel-Air, как живут?
Хм, это может быть в порядке.
Teper' eto istoriya o tom, kak vse
Moya zhizn' stala perevernuto-perevernulos'
I ya khotel by zanyat' minutu
Prosto sidet' pryamo tam
YA rasskazhu vam, kak ya stal knyazem v gorode pod nazvaniyem Bel-Air

V Zapadnoy Filadel'fii rodilsya i vyros
Na sportivnoy ploshchadke bylo gde ya provel bol'shuyu chast' moikh dney
CHILLIN 'iz Maxin' relaksin 'vse kruto
I vse rasstrelivayet bi-myach za predely shkoly
Kogda para parney, kotoryye byli do ni k chemu khoroshemu
Nachal nepriyatnosti v moyem rayone
YA poluchil v odnoy malen'koy bor'be i moya mama ispugalas'
Ona skazala: "Ty dvigayesh'sya" s tetey i dyadey v Bel-Air ».

YA prosil i umolyal yeye den' za dnem
No ona upakovala svoy chemodan i poslal menya na moyem puti
Ona dala mne potseluy, a potom ona dala mne svoy bilet.
YA polozhil na Walkman i skazal: "YA mog by takzhe udar yego."

Pervyy klass, yo, eto plokho
Pit'yevaya apel'sinovyy sok iz shampanskogo.
Yavlyayetsya li eto to, chto lyudi Bel-Air, kak zhivut?
Khm, eto mozhet byt' v poryadke.

**Comment by samGNSS** [comment]
wow, google translate is hilarious
